FROM node:20.5.1-alpine AS builder

RUN apk add --no-cache openssh git

WORKDIR /app
ADD package.json .
ADD package-lock.json .
RUN npm install
ADD . /app

ENV REACT_APP_ENV=production
ENV REACT_APP_BACKEND_HOST=backend-demo.mervarch.com

RUN npm build

FROM node:20.5.1-alpine
EXPOSE 3000
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/build /app/build
CMD ["serve", "-s", "build"]
