version: '3.8'

services:
  backend-demo:
    image: localhost:5000/merv-backend:e249fc5
    deploy:
      update_config:
        monitor: 30s
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.services.mervarch-backend-demo.loadbalancer.server.port=4000
        - traefik.http.routers.mervarch-backend-demo-https.rule=Host(`backend-demo.mervarch.com`)
        - traefik.http.routers.mervarch-backend-demo-https.entrypoints=https
        - traefik.http.routers.mervarch-backend-demo-https.tls.certresolver=le
    networks:
      feasible:

  demo:
    image: localhost:5000/merv-frontend:e249fc5
    deploy:
      update_config:
        monitor: 30s
        delay: 10s
        failure_action: rollback
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.http.services.mervarch-demo.loadbalancer.server.port=3000
        - traefik.http.routers.mervarch-demo-https.rule=Host(`demo.mervarch.com`)
        - traefik.http.routers.mervarch-demo-https.entrypoints=https
        - traefik.http.routers.mervarch-demo-https.tls.certresolver=le
    networks:
      feasible:

networks:
  feasible:
    external: true
