FROM elixir:1.16-alpine

WORKDIR /app

EXPOSE 4000

RUN apk add --no-cache curl
RUN mix local.hex --force && \
mix local.rebar --force

ENV PORT=4000
ENV MIX_ENV=prod
ENV MONGO_HOSTNAME=mongo
ENV MONGO_DATABASE=merv
ENV POSTGRES_HOSTNAME=postgres
ENV POSTGRES_EVENT_STORE_DB=merv_es
ENV SECRET_KEY_BASE=3Z7WuRc5DqQ5B6bDFWXIPzPdks5IGecM5WC+J8Dhuz0nhKmQf8NzlSsqy4c3BtPD

COPY . .
RUN mix do deps.get, deps.compile, compile
CMD ["mix", "phx.server"]
