FROM elixir:1.16-alpine
WORKDIR /app
RUN apk add --no-cache curl
RUN mix local.hex --force && \
mix local.rebar --force
EXPOSE 4000
ENV PORT=4000
ENV MIX_ENV=prod
ENV MONGO_HOSTNAME=common_mongo
ENV MONGO_DATABASE=merv
ENV POSTGRES_HOSTNAME=common_postgres
ENV POSTGRES_EVENT_STORE_DB=merv_es
ENV SECRET_KEY_BASE=3Z7WuRc5DqQ5B6bDFWXIPzPdks5IGecM5WC+J8Dhuz0nhKmQf8NzlSsqy4c3BtPD

COPY . .
RUN mix do deps.get, deps.compile, compile
CMD ["mix", "phx.server"]
